/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import hotel.modelo.Habitacion;
import hotel.modelo.Hotel;
import hotel.modelo.Huesped;
import hotel.modelo.Reserva;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author gomez
 */
public class FrmHotel extends javax.swing.JFrame {

    /**
     * Creates new form FrmHotel
     */
    public FrmHotel() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtfechain = new javax.swing.JTextField();
        txtfechafin = new javax.swing.JTextField();
        cbxhabitaciones = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setBackground(new java.awt.Color(102, 255, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reservacion");

        jLabel1.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("DNI:");

        jLabel5.setText("Habitacion:");

        jLabel6.setText("Fecha Inicio:");

        jLabel7.setText("Fecha Fin:");

        txtapellido.setAutoscrolls(false);

        txtfechain.setText("dd mm yyyy");
        txtfechain.setToolTipText("");
        txtfechain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechainActionPerformed(evt);
            }
        });

        txtfechafin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtfechafin.setText("dd-mm-yyyy");

        cbxhabitaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suit", "Doble", "Simple", "Triple" }));

        jButton1.setText("Registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtapellido)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtdni)
                    .addComponent(txtfechain, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(txtfechafin, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(cbxhabitaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(cbxhabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechain, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Hotel hotel = new Hotel();
        
        // Crear un mapa para gestionar habitaciones por tipo
    Map<String, List<Habitacion>> habitacionesDisponibles = new HashMap<>();

    // Crear y añadir habitaciones por tipo
    List<Habitacion> suits = new ArrayList<>();
    suits.add(new Habitacion(101, "Suit", 300000.00));
    suits.add(new Habitacion(105, "Suit", 300000.00));
    suits.add(new Habitacion(109, "Suit", 300000.00));

    List<Habitacion> dobles = new ArrayList<>();
    dobles.add(new Habitacion(102, "Doble", 150000.00));
    dobles.add(new Habitacion(106, "Doble", 150000.00));
    dobles.add(new Habitacion(110, "Doble", 150000.00));
    
    List<Habitacion> simple = new ArrayList<>();
    suits.add(new Habitacion(103, "simple", 100000.00));
    suits.add(new Habitacion(107, "simple", 100000.00));
    suits.add(new Habitacion(111, "simple", 100000.00));

    List<Habitacion> triple = new ArrayList<>();
    dobles.add(new Habitacion(104, "triple", 170000.00));
    dobles.add(new Habitacion(108, "triple", 170000.00));
    dobles.add(new Habitacion(112, "triple", 170000.00));

    habitacionesDisponibles.put("Suit", suits);
    habitacionesDisponibles.put("Doble", dobles);
    habitacionesDisponibles.put("Simple", simple);
    habitacionesDisponibles.put("Triple", triple);

        
        String seleccion = cbxhabitaciones.getSelectedItem().toString();
        Habitacion habitacion=null;

       List<Habitacion> habitacionesTipoSeleccionado = habitacionesDisponibles.get(seleccion);

    if (habitacionesTipoSeleccionado != null && !habitacionesTipoSeleccionado.isEmpty()) {
        // Asignar la primera habitación disponible
        habitacion = habitacionesTipoSeleccionado.remove(0);
        hotel.addHabitacion(habitacion); // Añadir la habitación al hotel
    } else {
        JOptionPane.showMessageDialog(null, "No hay habitaciones disponibles del tipo seleccionado.");
        return; // Salir si no hay habitaciones disponibles
    }

        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String dni = txtdni.getText();

        Huesped huesped1 = new Huesped(nombre, apellido, dni);
        //   Huesped huesped2 = new Huesped("Pedro","Gonzalez","1080456780");

        //String fechatxt = txtfechain.getText();
        //  String fechafintxt = txtfechafin.getText();
        //  LocalDate fechaInicio = LocalDate.parse(fechatxt);
        // LocalDate fechaFin = LocalDate.parse(fechafintxt);
        String fechaTexto = txtfechain.getText();   // AQUI INTENTO TRAER LA FECHA DEL TXT Y DESCARGARLO COMO UNA VARIABLE DE FECHA
        String fechaTextoFin = txtfechafin.getText();
        // Definir el formato de la fecha
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        try {
            // Convertir el texto a LocalDate
            LocalDate fechaInicio = LocalDate.parse(fechaTexto, formatter);
            LocalDate fechaFin = LocalDate.parse(fechaTextoFin, formatter);

            // Verificar que fechaInicio es anterior o igual a fechaFin
            if (fechaInicio.isAfter(fechaFin)) {
                JOptionPane.showMessageDialog(null, "Error: La fecha de inicio debe ser anterior o igual a la fecha de fin.");
                return; // Salir del método si las fechas no son válidas
            }

            if (hotel.isHabitacionDisponible(habitacion.getNumeroHabitacion(), fechaInicio, fechaFin)) {

                Reserva reserva1 = new Reserva(huesped1, habitacion, fechaInicio, fechaFin);

                hotel.addReserva(reserva1);
                JOptionPane.showMessageDialog(null, "Reservacion agregada con exito, el costo del servicio es de: " + reserva1.getCostoTotal() + " a nombre de: " + reserva1.getHuesped() + " habitacion " + habitacion);

            } else {
                JOptionPane.showMessageDialog(null, "La habitacion no esta disponible");
            }
           

        } catch (DateTimeParseException e) {
            // Manejar el error si el formato de la fecha no es válido
            JOptionPane.showMessageDialog(null, "Error: Formato de fecha incorrecto.");
        }

        /* if(hotel.isHabitacionDisponible(habit2.getNumeroHabitacion(), fechaInicio, fechaFin)){
           
           Reserva reserva2 = new Reserva(huesped2, habit2, fechaInicio, fechaFin);
              
           hotel.addReserva(reserva2);
            JOptionPane.showMessageDialog(null, "Reservacion agregada con exito, el costo del servicio es de: "+reserva2.getCostoTotal()+" a nombre de: "+reserva2.getHuesped());
           
       }else{
            JOptionPane.showMessageDialog(null,"La habitacion no esta disponible");
       }*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfechainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxhabitaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfechafin;
    private javax.swing.JTextField txtfechain;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
